# Generated by Django 3.1.5 on 2021-01-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='link',
            field=models.CharField(default='', max_length=355),
        ),
    ]
