# Generated by Django 3.1.5 on 2021-03-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_lesson_repl_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileoftask',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
