# Generated by Django 3.1.5 on 2021-03-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_lesson_repl_name'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourses',
            name='my_courses',
            field=models.ManyToManyField(related_name='my_courses', to='main.Course'),
        ),
        migrations.AlterField(
            model_name='usercourses',
            name='last_courses',
            field=models.ManyToManyField(related_name='last_courses', to='main.Course'),
        ),
    ]
