# Generated by Django 3.1.5 on 2021-03-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_lesson_repl_name'),
        ('user_profile', '0002_auto_20210302_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourses',
            name='last_courses',
            field=models.ManyToManyField(blank=True, related_name='last_courses', to='main.Course'),
        ),
        migrations.AlterField(
            model_name='usercourses',
            name='my_courses',
            field=models.ManyToManyField(blank=True, related_name='my_courses', to='main.Course'),
        ),
    ]
