# Generated by Django 3.1.5 on 2021-02-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_fileoftask_taskforlesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskforlesson',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
