# Generated by Django 3.1.5 on 2021-02-22 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_taskforlesson_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskforlesson',
            name='name',
        ),
    ]
