# Generated by Django 3.1.5 on 2021-02-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='repl_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
